// === THIS PROJECT INCLUDES ===

#include "data_loading/load_map.h"
#include "drawing/drawing.h"
#include "logging/logging.h"

#include "drawing/random_colors.h"
#include "edgevis/structs/mesh.h"
#include "edgevis/structs/edge.h"
#include "edgevis/structs/searchnode.h"
#include "edgevis/search/expansion.h"
#include "edgevis/search/visibility.h"

#include "drawing/cairo_geom_drawer.h"

#include "geomMesh/parsers/map_parser.h"
#include "polyanya/search/polyviz.h"
#include "utils/simple_clock.h"

#include <iomanip>
#include <boost/program_options.hpp>
#include <boost/filesystem.hpp>
#ifndef INPUT_MAPS_DIR
#define INPUT_MAPS_DIR "."
#endif

namespace po = boost::program_options;
namespace fs = boost::filesystem;
namespace cgm = cairo_geom_drawer;

/*
 * Argument parsing taken from trivis_examples.cc
*/

struct ProgramOptionVariables {
    std::string input_map_name = "undefined";
    std::string input_map_extension = ".mesh";
    std::string input_map_dir = INPUT_MAPS_DIR;
    std::string input_map_full_path;
    std::string mesh_type = "triangular";
    bool debug = false;
    bool save = false;
    bool heatmap = false;
    double map_scale = -1.0;
    double vis_radius = -1.0;
    int n_random_samples = 1;
    unsigned random_seed = std::random_device{}();
};

void AddProgramOptions(
        po::options_description &options_description,
        ProgramOptionVariables &pov
) {
    options_description.add_options()
            ("help,h", "Produce this help message. \n (*) Overwrites options: all.")
            ("map-name,m",
             po::value(&pov.input_map_name)->default_value(pov.input_map_name),
             "Map name.")
            ("map-ext",
             po::value(&pov.input_map_extension)->default_value(pov.input_map_extension),
             "Map file extension.")
            ("map-dir",
             po::value(&pov.input_map_dir)->default_value(pov.input_map_dir),
             "Map file directory.")
            ("map",
             po::value(&pov.input_map_full_path)->default_value(pov.input_map_full_path),
             "Full path to the map file. \n (*) Overwrites options: map_name, map_ext, map_dir.")
            ("map-scale,s",
             po::value(&pov.map_scale),
             "Map scale (optional).")
            ("mesh-type,t",
             po::value(&pov.mesh_type)->default_value(pov.mesh_type),
             "Type of used mesh - (triangular, polygonal) - default: polygonal.")
            ("vis-radius,r",
             po::value(&pov.vis_radius)->default_value(pov.vis_radius),
             "Visibility radius (-1 ~ infinite).")
            ("n-random-samples,n",
             po::value(&pov.n_random_samples)->default_value(pov.n_random_samples),
             "How many random samples should be generated.")
            ("random-seed",
             po::value(&pov.random_seed)->default_value(pov.random_seed),
             "Seed for the random generator (generated by std::random_device{}() by default).")
            ("debug",
             po::bool_switch(&pov.debug)->default_value(pov.debug),
             "Run in debug mode.")
            ("save",
             po::bool_switch(&pov.save)->default_value(pov.save),
             "Log resulting polygons to files (cannot measure performance)..")
            ("heatmap",
             po::bool_switch(&pov.heatmap)->default_value(pov.heatmap),
             "Create heatmap of computation time");
}

char ParseProgramOptions(
        int argc,
        const char *const *argv,
        ProgramOptionVariables &pov
) {
    po::variables_map vm;
    po::options_description command_line_options;
    po::options_description options_description("General options");
    AddProgramOptions(options_description, pov);
    try {
        // Parse the command line arguments.
        command_line_options.add(options_description);
        po::store(po::parse_command_line(argc, argv, command_line_options), vm);
        po::notify(vm);
    } catch (const std::exception &e) {
        return 'e';
    }
    if (vm.count("help")) {
        // If '-h' or '--help' option, print the options and return 'h'.
        command_line_options.print(std::cout, 80);
        return 'h';
    }
    // Make input_file_name, input_file_extension, input_file_dir, and input_file_full_path consistent.
    if (pov.input_map_full_path.empty()) {
        pov.input_map_full_path = pov.input_map_dir + "/" + pov.input_map_name + (pov.input_map_extension.empty() ? "" : pov.input_map_extension);
    } else {
        auto aux = fs::path(pov.input_map_full_path);
        pov.input_map_name = fs::change_extension(aux, "").filename().string();
        pov.input_map_extension = aux.extension().string();
        pov.input_map_dir = aux.parent_path().string();
    }
    return '0';
}

int body(ProgramOptionVariables pov)
{
    double time;
    custom::utils::SimpleClock clock;

    std::cout << "Preparing meshes, initializing Edgevis, TriVis and PolyVis solvers.\n";

    parsers::MapParser mapParser;
    parsers::Fade2DMesh fade2DMesh;
    parsers::MergedMesh mergedMesh;
    parsers::GeomMesh geomMeshTri;
    parsers::GeomMesh geomMeshPoly;
    parsers::GeomMesh IronHarvest;

    std::string mapName = pov.input_map_full_path;

    /*
     * mapParser.convertMapToFade2DMesh(mapName, fade2DMesh);
     * mapParser.convertMapToMergedMesh(mapName, mergedMesh);
     * mapParser.convertMergedMeshToGeomMesh(mergedMesh, geomMeshPoly);
     * mapParser.convertFade2DMeshToGeomMesh(fade2DMesh, geomMeshTri);
     */
    mapParser.readGeomMeshFromIronHarvestMesh(mapName,
                                              IronHarvest);
    //std::string filename = "/home/jakub/Projects/IronHarvest/mesh-maps/iron-harvest/scene_mp_2p_01.mesh";


    std::mt19937 rng(pov.random_seed); // random generator

    std::vector<edgevis::Point> verticesPoly;
    std::vector<edgevis::Point> r_points;
    std::vector<polyanya::Point> p_points;

    edgevis::Point p;
    polyanya::Point anyaP;

    std::vector<Point> r_v;
    std::vector<Point> l_v;
    std::vector<Point> v;

    std::string name;
    parsers::GeomMesh geomMesh;
    if(pov.mesh_type == "polygonal"){
        geomMesh = geomMeshPoly;
    }else if(pov.mesh_type == "triangular"){
        geomMesh = geomMeshTri;
    }else{
        std::cout << "Unknown mesh type.\n";
        return -1;
    }
    geomMesh = IronHarvest;

    edgevis::Mesh edgemesh;
    edgemesh.read(geomMesh);
    edgemesh.precalc_point_location();
    edgemesh.calculate_edges();

    clock.Restart();
    for (int i = 0; i < pov.n_random_samples; i++) {
        auto rp = edgemesh.random_point(rng);
        p.x = rp.x;
        p.y = rp.y;
        anyaP.x = rp.x;
        anyaP.y = rp.y;
        r_points.push_back(p);
        p_points.push_back(anyaP);
    }
    time = clock.TimeInSeconds();
    std::cout << pov.n_random_samples << " random points generated in: " << time << " seconds." << std::endl;

    PolyVis solverPoly(geomMesh);
    edgevis::EdgeVisibility Evis(edgemesh);
    Evis.set_visual_mesh(geomMesh);

    std::vector<polyanya::Point> verticesPolyAnya;
    std::cout << "\n\nMap: " << pov.input_map_name
              << "\nType of mesh: " << pov.mesh_type
              << "\nNumber of iterations: " <<  pov.n_random_samples;
    std::cout << "\n" << std::endl;

    clock.Restart();
    Evis.precompute_edges_searchnodes();
    time = clock.TimeInSeconds();
    std::cout << "\nEdgevis\n";
    std::cout << "Preprocessing time for Edge Visibility was " <<
              time << " seconds.\n";
    clock.Restart();
    Evis.precompute_edges_optimnodesV1();
    time = clock.TimeInSeconds();
    std::cout << "Preprocessing time for OptimNodesV1 was " <<
              time << " seconds.\n";


    bool debug = pov.debug;
    bool save = pov.save;
    bool heatmap = pov.heatmap;
    std::ofstream outfile;
    std::ofstream outfile_polyvis;
    std::ofstream results;
    results.open("results.dat", std::ios::out | std::ios::trunc );
    results << pov.input_map_name
            << "\nType of mesh: " << pov.mesh_type
            << "\nNumber of iterations: " <<  pov.n_random_samples
            << "\n=======================================================\n";
    if(save){
        outfile.open("logger_edgevis.dat", std::ios::out | std::ios::trunc );
        outfile_polyvis.open("logger_polyvis.dat", std::ios::out | std::ios::trunc );
    }

    std::vector<double> times;
    double tMax = 0, tMin = 100, t;
    clock.Restart();
    for (auto pos : r_points){
        if(debug) {
            Evis.reset_visu();
            std::string m = pov.input_map_name + ".png";
            rename("debug_visu.png",  m.c_str());
        }

        verticesPoly = Evis.find_point_visibility(pos, debug);
        if(heatmap){
            t = clock.TimeInSeconds();
            times.push_back(t);
            tMax = std::max(tMax, t);
            tMin = std::min(tMin, t);
        }

        if(save){
            outfile << "--\n";
            outfile << pos << std::endl;
            outfile << verticesPoly.size() << std::endl;
            for (auto p : verticesPoly){
                outfile << p << "; ";
            }
            outfile << std::endl;
        }
        if(debug) {
            anyaP.x = pos.x;
            anyaP.y = pos.y;
            verticesPolyAnya = solverPoly.get_visibility_polygon(anyaP);

            Evis.visualise_point(pos, 0);
            Evis.visualise_polygon(verticesPoly, 2);
            verticesPoly.resize(verticesPolyAnya.size());
            for (int i = 0; i < verticesPolyAnya.size(); i++) {
                verticesPoly[i].x = verticesPolyAnya[i].x;
                verticesPoly[i].y = verticesPolyAnya[i].y;
            }
            Evis.visualise_polygon(verticesPoly, 1);
            getchar();
        }

    }
    time = clock.TimeInSeconds();
    std::cout << "Total computation time: " << time << " seconds.\n";
    std::cout << "Mean computation time: " << time/pov.n_random_samples << " seconds/point.\n";
    results << "EdgeVis:";
    results << "\nTotal computation time:" << time <<
              "\nAverage computation time per point:" << time/pov.n_random_samples << std::endl;

    if(heatmap)
        Evis.visualise_heatmap(r_points, times, tMax, tMin);

    clock.Restart();
    for (auto pos : p_points){
        verticesPolyAnya = solverPoly.get_visibility_polygon(pos);
        if(save){
            outfile_polyvis << "--\n";
            outfile_polyvis << pos << std::endl;
            outfile_polyvis << verticesPolyAnya.size() << std::endl;
            for (auto p : verticesPolyAnya){
                outfile_polyvis << p << "; ";
            }
            outfile_polyvis << std::endl;

        }
    }
    time = clock.TimeInSeconds();
    std::cout << "\nPolyVis\n";
    std::cout << "Total computation time: "<< time << " seconds.\n";
    std::cout << "Mean computation time: "<< time/pov.n_random_samples << " seconds/point.\n";

    results << "\n===============================================================\n";
    results << "PolyVis:";
    results << "\nTotal computation time:" << time <<
            "\nAverage computation time per point:" << time/pov.n_random_samples << std::endl;

    results.close();
    return 0;
}

int main(
        int argc,
        const char *const *argv
) {
    ProgramOptionVariables pov;
    char c = ParseProgramOptions(argc, argv, pov);
    if (c == 'h') {
        return EXIT_SUCCESS;
    } else if (c == 'e') {
        return EXIT_FAILURE;
    } else {
        return body(pov);
    }
}
